sudo: required
services:
  - docker
before_install:
  - sudo docker pull demonchild2112/grr_centos:7
  - sudo docker create -it demonchild2112/grr_centos:7
  - sudo docker start $(docker ps -a -q)
  - sudo docker exec --user 0 $(docker ps -a -q) adduser -m grrbot
  - sudo docker cp run_centos_docker_workflow.sh $(docker ps -a -q):/home/grrbot
  - sudo docker exec --user 0 $(docker ps -a -q) chown grrbot:grrbot /home/grrbot/run_centos_docker_workflow.sh
install:
  - sudo docker exec -it --user grrbot $(docker ps -a -q) /home/grrbot/run_centos_docker_workflow.sh
