matrix:
  include:
    # 64-bit deb builds
    - os: linux
      language: python
      python: 2.7
      sudo: false
      addons:
        apt:
          packages:
            - fakeroot
            - debhelper
            - libffi-dev
            - libssl-dev
            - python-dev
      env:
        - GCS_TAG=ubuntu_64bit
        - GCS_BUCKET=ogaro-travis-test
        - PROTOC="${HOME}/protobuf/bin/protoc"
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - travis/set_up_gcs_auth.sh
        - travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - pip install --upgrade virtualenv
        - virtualenv "${HOME}/INSTALL"
      install:
        - travis/install.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        - grr_run_tests --processes=2
        - travis/build_templates.sh
        - travis/deploy_to_gcs.sh

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/protobuf
