matrix:
  include:
    # OSX
    - os: osx
      # psutil fails to install on the default beta-xcode6.1
      osx_image: xcode6.4
      language: generic
      python: 2.7
      sudo: required
      env:
        - PROTOC="${HOME}/protobuf/bin/protoc"
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - /bin/bash travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - brew install libffi
        - git clone https://github.com/MacPython/terryfy
        - source terryfy/travis_tools.sh
        - get_python_environment macpython 2.7.11
        - pip install --upgrade virtualenv
        - virtualenv "${HOME}/INSTALL"
      install:
        - /bin/bash travis/install.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        - grr_run_tests --processes=2 --labels=client_action
        - /bin/bash travis/build_templates.sh
        - /bin/bash travis/deploy_to_gcs.sh

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/protobuf
