matrix:
  include:
    # OSX builds
    - os: osx
      # psutil fails to install on the default beta-xcode6.1
      osx_image: xcode9.2
      python: 2.7
      sudo: required
      env:
        - GCS_TAG=osx
        - GCS_BUCKET=ogaro-travis-test
        - PROTOC="${HOME}/protobuf/bin/protoc"
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - travis/set_up_gcs_auth.sh
        - travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - brew install libffi
        - git clone https://github.com/MacPython/terryfy
        - source terryfy/travis_tools.sh
        - get_python_environment macpython 2.7.11
        - pip install --upgrade virtualenv
        - virtualenv "${HOME}/INSTALL"
      install:
        - travis/install_client_only.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        # TODO(ogaro): Uncomment when we have a final solution for testing on MacOS.
        #- pytest grr/client/grr_response_client/ --ignore grr/server/grr_response_server/gui/selenium_tests/ --ignore grr/client/grr_response_client/linux/ --ignore grr/client/grr_response_client/client_actions/linux/
        - travis/build_templates.sh
        - travis/deploy_to_gcs.sh

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/protobuf
