matrix:
  include:
    # 64-bit deb builds
    - os: linux
      language: python
      python: 2.7
      sudo: false
      addons:
        apt:
          packages:
            - fakeroot
            - debhelper
            - libffi-dev
            - libssl-dev
            - python-dev
      env:
        - GCS_TAG=ubuntu_64bit
        - PROTOC="${HOME}/protobuf/bin/protoc"
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - /bin/bash travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - pip install --upgrade virtualenv
        - virtualenv "${HOME}/INSTALL"
      install:
        - /bin/bash travis/install.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        # TODO(ogaro): Uncomment - grr_run_tests --processes=2
        - /bin/bash travis/build_templates.sh
        - /bin/bash travis/deploy_to_gcs.sh

    # OSX builds
    - os: osx
      # psutil fails to install on the default beta-xcode6.1
      osx_image: xcode6.4
      language: generic
      python: 2.7
      sudo: required
      env:
        - GCS_TAG=osx
        - PROTOC="${HOME}/protobuf/bin/protoc"
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - /bin/bash travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - brew install libffi
        - git clone https://github.com/MacPython/terryfy
        - source terryfy/travis_tools.sh
        - get_python_environment macpython 2.7.11
        - pip install --upgrade virtualenv
        - virtualenv "${HOME}/INSTALL"
      install:
        - /bin/bash travis/install.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        # TODO(ogaro): Uncomment - grr_run_tests --processes=2 --labels=client_action
        - /bin/bash travis/build_templates.sh
        - /bin/bash travis/deploy_to_gcs.sh

    # 64-bit Centos docker container inside an Ubuntu host, for rpm builds
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      env:
        - GCS_TAG=centos_64bit
        - DOCKER_IMG=centos:7
        - DOCKER_CONTAINER=centos_64bit_container
        - DOCKER_USER=grrbot
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - pip install google-compute-engine  # Needed for deploying to GCS
        # Create a Docker container which mounts the GRR repo in the
        # /mnt directory
        - >-
          sudo docker create -it
          --volume "${PWD}:/mnt"
          --workdir /mnt
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --env PROTOC="/home/${DOCKER_USER}/protobuf/bin/protoc"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - sudo docker start "${DOCKER_CONTAINER}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          /mnt/travis/install_centos_prereqs.sh
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          /mnt/travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          /mnt/travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          /mnt/travis/install.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/build_templates.sh
        # Test installing the built rpm (as root)
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          rpm -vih /mnt/built_templates/*.rpm
        - /bin/bash travis/deploy_to_gcs.sh

    # 32-bit Ubuntu docker container inside a 64-bit host, for 32-bit deb builds
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      env:
        - GCS_TAG=ubuntu_32bit
        - DOCKER_IMG=demonchild2112/ubuntu_i386:xenial
        - DOCKER_CONTAINER=ubuntu_32bit_container
        - DOCKER_USER=grrbot
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - pip install google-compute-engine  # Needed for deploying to GCS
        # Create a Docker container which mounts the GRR repo in the
        # /mnt directory
        - >-
          sudo docker create -it
          --volume "${PWD}:/mnt"
          --workdir /mnt
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --env PROTOC="/home/${DOCKER_USER}/protobuf/bin/protoc"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - sudo docker start "${DOCKER_CONTAINER}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          linux32 /mnt/travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 /mnt/travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 /mnt/travis/install.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 travis/build_templates.sh
        - /bin/bash travis/deploy_to_gcs.sh

    # 32-bit Centos docker container inside a 64-bit host, for 32-bit rpm builds
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      env:
        - GCS_TAG=centos_32bit
        - DOCKER_IMG=demonchild2112/centos_i686:7
        - DOCKER_CONTAINER=centos_32bit_container
        - DOCKER_USER=grrbot
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - pip install google-compute-engine  # Needed for deploying to GCS
        # Create a Docker container which mounts the GRR repo in the
        # /mnt directory
        - >-
          sudo docker create -it
          --volume "${PWD}:/mnt"
          --workdir /mnt
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --env PROTOC="/home/${DOCKER_USER}/protobuf/bin/protoc"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - sudo docker start "${DOCKER_CONTAINER}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          linux32 /mnt/travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 /mnt/travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 /mnt/travis/install.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          linux32 /mnt/travis/build_templates.sh
        - /bin/bash travis/deploy_to_gcs.sh

    # End-to-end tests                                                                                                                                     
    - os: linux
      language: python
      python: 2.7
      sudo: required
      addons:
        apt:
          packages:
            - fakeroot
            - debhelper
            - libffi-dev
            - libssl-dev
            - python-dev
      env:
        - GCS_TAG=end_to_end_tests
        - PROTOC="${HOME}/protobuf/bin/protoc"
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - /bin/bash travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - pip install --upgrade virtualenv
        - virtualenv "${HOME}/INSTALL"
      install:
        - /bin/bash travis/install.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        - /bin/bash travis/build_server_deb.sh
        - /bin/bash travis/deploy_to_gcs.sh

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/protobuf
