env:
  global:  # These variables are common to all jobs.
    - PROTOC="${HOME}/protobuf/bin/protoc"
    - PATH=$PATH:${HOME}/google-cloud-sdk/bin
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1

matrix:
  include:
    # Ubuntu (the default OS for Travis)
    - os: linux
      language: python
      python: 2.7
      sudo: false
      addons:
        apt:
          packages:
            - libffi-dev
            - libssl-dev
            - python-dev
      before_install:
        - /bin/bash travis/install_protobuf.sh $TRAVIS_OS_NAME
        # We upgrade pip inside the virtualenv to avoid sudo here.
        - pip install --upgrade virtualenv
        - virtualenv ${HOME}/INSTALL
      install:
        - /bin/bash travis/install.sh
      script:
        - source ${HOME}/INSTALL/bin/activate
        - grr_run_tests --processes=2
        - /bin/bash travis/deploy_to_gcs.sh

    # OSX
    - os: osx
      # psutil fails to install on the default beta-xcode6.1
      osx_image: xcode6.4
      language: generic
      python: 2.7
      sudo: required
      before_install:
        - /bin/bash travis/install_protobuf.sh $TRAVIS_OS_NAME
        - brew update
        - brew install libffi
        - git clone https://github.com/MacPython/terryfy
        - source terryfy/travis_tools.sh
        - get_python_environment macpython 2.7.11
        # We upgrade pip inside the virtualenv to avoid sudo here.
        - pip install --upgrade virtualenv
        - virtualenv ${HOME}/INSTALL
      install:
        - /bin/bash travis/install.sh
      script:
        - source ${HOME}/INSTALL/bin/activate
        - grr_run_tests --processes=2 --labels=client_action
        - /bin/bash travis/deploy_to_gcs.sh

    # Centos docker container inside an Ubuntu host
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      env: # TODO(ogaro): Set protoc and travis os name explicitly here.
        - DOCKER_IMG=centos:7
        - DOCKER_CONTAINER=grr_container
        - DOCKER_USER=grrbot
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - sudo /bin/bash travis/centos/before_install.sh
      install:
        - sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}" /mnt/travis/centos/docker_install.sh
      script:
        - sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}" /mnt/travis/centos/docker_script.sh
        - sudo docker exec --user root "${DOCKER_CONTAINER}" rpm -vih /mnt/built_templates/*.rpm
        - /bin/bash travis/centos/deploy.sh

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/protobuf
