matrix:
  include:
    # 64-bit Centos 7 docker container inside an Ubuntu host, for rpm builds
    - os: linux
      dist: trusty
      sudo: required
      services:
        - docker
      env:
        - GCS_TAG=centos_64bit
        - GCS_BUCKET=ogaro-travis-test
        - DOCKER_IMG=centos:7
        - DOCKER_CONTAINER=centos_64bit_container
        - DOCKER_USER=grrbot
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - pip install google-compute-engine
        - travis/set_up_gcs_auth.sh
        # Create a Docker container which mounts the GRR repo in the
        # /mnt directory
        - >-
          sudo docker run -dit
          --volume "${PWD}:/mnt/grr"
          --workdir /mnt/grr
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --env PROTOC="/home/${DOCKER_USER}/protobuf/bin/protoc"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          yum install -y epel-release python-devel wget which java-1.8.0-openjdk
          libffi-devel openssl-devel zip git gcc gcc-c++ redhat-rpm-config
          rpm-build rpm-sign
        - sudo docker exec "${DOCKER_CONTAINER}" yum install -y python-pip
        - sudo docker exec "${DOCKER_CONTAINER}" pip install --upgrade pip virtualenv
        - sudo docker exec "${DOCKER_CONTAINER}" travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install_client_only.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/build_templates.sh
        # Test installing the built rpm (as root)
        - sudo docker exec "${DOCKER_CONTAINER}" rpm -vih gcs_upload_dir/*.rpm
        - travis/deploy_to_gcs.sh

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/protobuf
