matrix:
  include:
  - os: linux
    language: python
    python: 2.7
    sudo: required
services:
  - docker
before_install:
  - sudo docker pull centos:7
  - sudo docker create -it -v $PWD:/mnt --name grr_container centos:7
  - sudo docker start grr_container
  - sudo docker exec grr_container /mnt/travis/centos/bare_centos_preinstall.sh
  - sudo docker exec grr_container /mnt/travis/centos/setup_test_user.sh
install:
  - sudo docker exec --user grrbot grr_container /mnt/travis/centos/run_centos_docker_workflow.sh
script:
  - sudo docker exec -it --user root grr_container rpm -vih /mnt/built_templates/*.rpm
