matrix:
  include:
    # End-to-end tests
    - os: linux
      sudo: required
      env:
        - GCS_TAG=end_to_end_tests
        - DOCKER_USER=grrbot
        - DOCKER_CONTAINER=centos_64bit_container
        - DOCKER_IMG=ubuntu:xenial
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - pip install google-compute-engine
        - >-
          sudo docker run -dit
          --volume "${PWD}:/mnt"
          --workdir /mnt
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --env PROTOC="/home/${DOCKER_USER}/protobuf/bin/protoc"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}" apt-get update
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          apt-get install -y fakeroot debhelper libffi-dev libssl-dev python-dev
          python-pip wget openjdk-8-jdk zip git debchange
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          pip install --upgrade pip virtualenv
        - sudo docker exec "${DOCKER_CONTAINER}" travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/build_server_deb.sh
        - travis/deploy_to_gcs.sh
