matrix:
  include:
    # 64-bit deb builds
    - os: linux
      language: python
      python: 2.7
      sudo: false
      addons:
        apt:
          packages:
            - fakeroot
            - debhelper
            - libffi-dev
            - libssl-dev
            - python-dev
      env:
        - GCS_TAG=ubuntu_64bit
        - GCS_BUCKET=ogaro-travis-test
        - PROTOC="${HOME}/protobuf/bin/protoc"
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - travis/set_up_gcs_auth.sh
        - travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - pip install --upgrade virtualenv
        - virtualenv "${HOME}/INSTALL"
      install:
        - travis/install.sh
      script:
        - source "${HOME}/INSTALL/bin/activate"
        - grr_run_tests --processes=2

    - os: linux
      dist: trusty
      sudo: required
      env:
        - GCS_TAG=server_deb
        - GCS_BUCKET=ogaro-travis-test
        - DOCKER_IMG=ubuntu:xenial
        - DOCKER_CONTAINER=xenial_64bit_container
        - DOCKER_USER=grrbot
        - PATH=$PATH:${HOME}/google-cloud-sdk/bin
        - CLOUDSDK_CORE_DISABLE_PROMPTS=1
      before_install:
        - pip install google-compute-engine
        - travis/set_up_gcs_auth.sh
        - >-
          sudo docker run -dit
          --volume "${PWD}:/mnt/grr"
          --workdir /mnt/grr
          --env DOCKER_USER="${DOCKER_USER}"
          --env TRAVIS_OS_NAME="${TRAVIS_OS_NAME}"
          --env PROTOC="/home/${DOCKER_USER}/protobuf/bin/protoc"
          --env TRAVIS_COMMIT="${TRAVIS_COMMIT}"
          --name "${DOCKER_CONTAINER}"
          "${DOCKER_IMG}"
        - >-
          sudo docker exec "${DOCKER_CONTAINER}" apt-get update
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          apt-get install -y fakeroot debhelper libffi-dev libssl-dev python-dev
          python-pip wget openjdk-8-jdk zip git
        - >-
          sudo docker exec "${DOCKER_CONTAINER}"
          pip install --upgrade pip virtualenv
        - sudo docker exec "${DOCKER_CONTAINER}" travis/set_up_test_user.sh
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install_protobuf.sh "${TRAVIS_OS_NAME}"
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          virtualenv "/home/${DOCKER_USER}/INSTALL"
      install:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          travis/install.sh
      script:
        - >-
          sudo docker exec --user "${DOCKER_USER}" "${DOCKER_CONTAINER}"
          /bin/bash -c "source /home/${DOCKER_USER}/INSTALL/bin/activate && grr_run_tests --processes=2"

cache:
  directories:
    - $HOME/.cache/pip
    - $HOME/protobuf
