branches:
  only:
    - master

platform:
  - x64

clone_folder: C:\grr_src

cache:
  - '%LOCALAPPDATA%\pip\Cache -> **\install_for_build.bat'

install:
  - C:\grr_src\vagrant\windows\install_for_build.bat
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt C:\grr_src\vagrant\windows\ogaro.appveyor-test.json.enc -secret %GCE_ENCRYPTION_KEY%

build_script:
  - C:\Python27-x64\python.exe C:\grr_src\vagrant\windows\build_windows_templates.py --grr_src=C:\grr_src --output_dir=C:\grr_src\output --test_repack_install
  - powershell C:\grr_src\vagrant\windows\deploy_to_gcs.ps1

artifacts:
  - path: output
    name: templates
    type: zip

environment:
  GCE_ENCRYPTION_KEY:
    # See https://www.appveyor.com/docs/how-to/secure-files/
    secure: V50YB9ZMPxsSwcmEPaD5qw==
