platform:
  - x64

clone_folder: C:\grr_src

cache:
  - '%LOCALAPPDATA%\pip\Cache -> **\install_for_build.bat'

install:
  - ps: if ($env:VAGRANT -eq 'false') { & C:\grr_src\vagrant\windows\install_for_build.bat }
  - ps: if ($env:VAGRANT -eq 'false') { nuget install secure-file -ExcludeVersion }
  # See https://www.appveyor.com/docs/how-to/secure-files/
  - >-
    secure-file\tools\secure-file
    -decrypt C:\grr_src\vagrant\windows\appveyor_uploader_service_account.json.enc
    -secret %GCS_ENCRYPTION_KEY%

build_script:
  - >-
    C:\Python27-x64\python.exe
    C:\grr_src\vagrant\windows\build_windows_templates.py
    --grr_src=C:\grr_src
    --output_dir=C:\grr_src\output
    --test_repack_install
  - powershell C:\grr_src\vagrant\windows\deploy_to_gcs.ps1

# TODO(ogaro): Create a shared appveyor account, and use its encryption key.
environment:
  GCS_BUCKET: ogaro-travis-test
  GCS_ENCRYPTION_KEY:
    secure: V50YB9ZMPxsSwcmEPaD5qw==
  matrix:
    - VAGRANT: false
    - VAGRANT: true
