branches:
  only:
    - master

platform:
  - x64

clone_folder: C:\grr_src

cache:
  - '%LOCALAPPDATA%\pip\Cache -> **\install_for_build.bat'

install:
  - cmd: C:\grr_src\vagrant\windows\install_for_build.bat
  - nuget install secure-file -ExcludeVersion
  - secure-file\tools\secure-file -decrypt C:\grr_src\vagrant\windows\ogaro.appveyor-test.json.enc -secret %gce_secret%

build_script:
  - cmd: C:\Python27-x64\python.exe C:\grr_src\vagrant\windows\build_windows_templates.py --grr_src=C:\grr_src --output_dir=C:\grr_src\output --test_repack_install
  - cmd: C:\grr_src\vagrant\windows\deploy_to_gcs.bat

artifacts:
  - path: output
    name: templates
    type: zip

environment:
  gce_secret:
    secure: V50YB9ZMPxsSwcmEPaD5qw==
