image: ubuntu

install:
- lsb_release -a
- sudo -H ./appveyor/linux/install_latest_server_deb.sh

artifacts:
- path: /usr/share/grr-server/lib/python2.7/site-packages/grr/var/log/grr-ui.log
  name: Server Logs

# Appveyor will try to build any C++ projects it finds if we do not disable this.
build: off
