image: ubuntu

environment:
  GRR_ADMIN_PASS: 'e2e_tests'

install:
- lsb_release -a
- sudo ./appveyor/linux/install_latest_server_deb.sh

artifacts:
- path: /usr/share/grr-server/lib/python2.7/site-packages/grr/var/log/*.log
  name: Server Logs

build: off
